### ISSUE TITLE
The first startup after installation will crash

### ISSUE THREAD

**Issue by chenhuicui** [michaelWuensch/BitBanana#72] opened 2024-01-31 08:12 UTC
## Description
The first startup after installation will crash

## Expected Behavior
successfully startup

## Actual Behavior
crash

## Steps to Reproduce

1.download from f-droid
2.install and startup crash

## Your Environment

- BitBanana version: _0.7.0_
- Android version: _android 10_
- Device: _huawei nova 5 pro_

**Comment by michaelWuensch** [comment] 2024-01-31 12:42
Thanks for reporting!
I'll check that when I am back from my holiday.
By the way, you seem to be on 0.7.0, 0.7.3 is already out, maybe it is already fixed.

**Comment by michaelWuensch** [comment] 2024-02-15 14:41
I tried with both 0.7.0 and 0.7.3, both did not crash on my Samsung S22 when I installed it.
Did you already have an older version of BitBanana installed before installing 0.7.0 from F-Droid?

**Comment by michaelWuensch** [comment] 2024-02-23 19:04
I'm closing this now as I cannot reproduce it and in the new 0.7.4 version that was just released the whole startup procedure was refactored.
If the issue persists for you, feel free to reopen it or create a new issue.

**Closed by michaelWuensch** 2024-02-23 19:04 UTC
