### ISSUE TITLE
USD amount far more than actual amount

### ISSUE THREAD

**Issue by HalFinneyIsMyHomeBoy** [michaelWuensch/BitBanana#71] opened 2024-01-22 18:33 UTC
It should be about $900, but it says much more.

![signal-2024-01-22-122951_002](https://github.com/michaelWuensch/BitBanana/assets/1430502/88681f50-85b3-4653-8b2a-f2d7788605da)

**Comment by michaelWuensch** [comment] 2024-01-23 13:03
Oh, wow, strange. Just checked mine, it shows correcly when switching to dollars.

Which exchange rate provider do you use (it can be set in advanced settings)

And is tor turned on in your settings menu?
Exchange rate requests are often blocked by cloudflare when done over tor. But normaly this can lead to old exchange rates not to incorrect ones. Still you could try to deactivate tor in the settings for a few minutes and see if it fixes the problem.

**Comment by michaelWuensch** [comment] 2024-01-24 13:36
@HalFinneyIsMyHomeBoy 
I can also see that the sum of your account balance details does not even match your over all balance at all. 🤔
What if you have sats as your primary currency... does the sum match then?

**Comment by HalFinneyIsMyHomeBoy** [comment] 2024-02-07 02:25
I apologize for the late reply, I switched the exchange rate provider to coinbase and that seems to have fixed that.

I have since closed all three of my channels ( was only experimenting with them temporarily )
I also tried changing the currency to sats.  Since all channels on my node have been closed for a week now , is it correct to still have a balance on it?   

![signal-2024-02-06-201552_002](https://github.com/michaelWuensch/BitBanana/assets/1430502/74e4811d-19d9-421d-b682-4c9f379bcce8)
![signal-2024-02-06-201630_002](https://github.com/michaelWuensch/BitBanana/assets/1430502/7a749542-b451-4991-b54f-c28b530b09b1)

**Comment by HalFinneyIsMyHomeBoy** [comment] 2024-02-07 17:56
Also, in regards to the incorrect sat balance, I recently closed all 3 channels on my Umbrel node (it was experimental anyway)
The wallet still said I had a balance on LN, I  uninstalled LND node from my Umbrel, reinstalled it and recovered with my seed.

Took a day or so to re-scan the blockchain, but after reconnecting BitBanana to my node, the correct sat and USD appears now.

Not sure if any of this info helps, but it's possible it had something to do with my Umbrel node.

**Comment by michaelWuensch** [comment] 2024-02-15 14:05
I am closing the issue now. I checked the code and I basically display whatever lnd returns. I cannot reproduce it and have the suspicion something weird was going on with your node.
Thanks for the info though!
In case you experience this again or someone else has a similar issue, please reopen the issue.

**Closed by michaelWuensch** 2024-02-15 14:05 UTC
Labels: :bug: bug
